### ISSUE TITLE
Validate does not work as expected

### ISSUE THREAD

**Issue by JTejedor** [GabrielMusat/pyargparse#1]
base_args.py 
```py
 def __validate(self):
        for arg in self._attr_map.values():
            if not hasattr(self, arg.name) or not arg.optional and getattr(self, arg.name) is None:
                print(f"argument '{arg.name}' is mandatory, but no value was provided")
                self._show_help()
                raise ArgumentError(f"argument '{arg.name}' is mandatory, but no value was provided")
```
The if clausule, I think that it makes any parameter as mandatory instead optional because lack of parenthesis.
Suggestion:
```py
    if not hasattr(self, arg.name) or (not arg.optional and getattr(self, arg.name) is None):
```

**Comment by gabotechs** [comment]
The parenthesis doesn't have any effect there, feel free to test `if False or (not False and True)` vs `if False or not False and True`.
In fact, there are already unit test cases that already cover the optional feature and are passing. It would be useful if you could provide a code snippet that replicates the problem
